In [660]:
import numpy as np
from numpy import nanmedian
#from scipy.fft import fft
import math
from numpy.fft import fft, ifft, rfft, fft2

# Função Filt5

In [3]:
#' filt5
#' @description  Finds maximum of a 5x5 sliding window. If the central pixel is the maximum, this is flagged as a one. All other pixels are flagged as zero. Usually this function is not used directly.
#' @usage filt5(lon, lat, ingrid, nodata = NA)
#' @param lon longitude (vector) of the satellite image
#' @param lat latitude (vector) of the satellite image
#' @param ingrid The satellite data (matrix)
#' @param nodata value representing 'no data'
#'
#' @return returns a grid of zeros and ones
#' @seealso \code{\link{boa}}
#' @export
#'
#' @examples 
#' # none
filt5 <-
function(lon , lat, ingrid, nodata = NA){
#======================================================#
# Find peaks in 5 directions. FLag as 5
#======================================================#
 #outgrid = matrix(0,nrow=dim(ingrid)[1],ncol=dim(ingrid)[2] ) # make all zeros..
 nodatidx = ingrid[ingrid==nodata]    # creates single dim array with as much values as the matrix ingrid, with NANs
 ingrid[nodatidx] = -9999
 outgrid = ingrid*0 ## outgrid is a matrix with the shape of ingrid, full of Zeros
 l1 = length(lon)
 l2 = length(lat)
for(i in 3:(l1-2)){
 for(j in 3:(l2-2)){
   subg = ingrid[(i-2):(i+2),(j-2):(j+2)]   #results in slice with data from row i-2 to i+2 (i-2,i-1, i, i+1, i+2) (included) and columns (j-2, j-1, j, j+1, j+2)
if(sum(is.na(subg))==25){
outgrid[i,j] = 0
}else{
vec = as.vector(subg)    ## convert matrix to vector
ma = which.max(subg)
mi = which.min(subg)

   if(ma==13||mi==13){
 outgrid[i,j] = 1
}else{
  outgrid[i,j] = 0
}
}
   }
  }
 ## não tou a perceber para que serve esta parte  
outgrid[nodatidx] = nodata  
outgrid

SyntaxError: invalid syntax (2922168994.py, line 15)

In [556]:
def filt5(lon, lat, ingrid, nodata=np.nan):
    """
    Find peaks in 5 directions. FLag as 5
    """
    
    nodatidx = ingrid.flatten()*np.nan ## creates single dim array with as much values as the matrix ingrid, with NANs
    outgrid = np.zeros(ingrid.shape)   ## outgrid is a matrix with the shape of ingrid, full of Zeros
    
    l1 = len(lon)
    l2 = len(lat)
    
    for i in range(3, l1-1):   #tem de ser -1 em vez de -2 
        for j in range(3, l2-1):
            subg = ingrid[(i-3):(i+2), (j-3):(j+2)] # slice with data from row (i-2,i-1, i, i+1, i+2) and columns (j-2, j-1, j, j+1, j+2)
            if np.isnan(subg).sum()==25:    #if all values in submatrix subg are null values:
                outgrid[i,j] = 0
            else:
                vec = np.array(subg).T.flatten()    ## convert matrix to vector
                ma = np.where(subg == np.amax(subg))
                mi = np.where(subg == np.amin(subg))
                
                if ma==(2,2) or mi==(2,2):     #se se tratar do valor meio da matrix
                    outgrid[i-1,j-1] = 1
                else:
                    outgrid[i,j] = 0
    
    #Não estou a perceber esta parte (esta em R, converter para python)
    #outgrid[nodatidx] = nodata
    return outgrid

                
                
    


#### Quanto à função filt5 só falta aquela ultima linha de código

## Verificação passo a passo da conversão da função filt5 de R para python

In [563]:
lon = np.array([1,2,3,4,5,6])
lat = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

ingrid = np.arange(1,91).reshape(6, 15)  

nodatidx = ingrid.flatten()*np.nan      #check
outgrid = np.zeros(ingrid.shape)        #check

l1 = len(lon)                           #check
l2 = len(lat)                           #check

for i in range(3, l1-1):   
    for j in range(3, l2-1):
        subg = ingrid[(i-3):(i+2), (j-3):(j+2)]       #check
        if np.isnan(subg).sum()==25:
            outgrid[i,j] = 0
        else:
            vec = np.array(subg).T.flatten()
            ma = np.argmax(subg.flatten())
            mi = np.argmin(subg.flatten())
            
            if ma==24 or mi==13:
                outgrid[i-1,j-1] = 1
            else:
                outgrid[i,j] = 0
                
            
outgrid

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# Função Filt3

In [ ]:
#' filt3
#'
#' @param lon longitude (vector) of the satellite image
#' @param lat latitude (vector) of the satellite image
#' @param ingrid The satellite data (matrix)
#' @param grid5 results of \code{\link{filt5}}
#'
#' @return returns a median smoothed grid of satellite data
#' @seealso \code{\link{boa}}
#' @usage filt3(lon, lat, ingrid, grid5 = grid5(lon, lat, ingrid))
#' @export
#'
#' @examples
#' # none here
filt3 <-
function(lon , lat, ingrid, grid5){
#======================================================#
# Find peaks in 3 directions. FLag as 3
#======================================================#
 outgrid = ingrid*0 # make all zeros..
 l1 = length(lon)
 l2 = length(lat)
for(i in 3:(l1-2)){
 for(j in 3:(l2-2)){
  if((grid5[i,j]==0)==T){
 subg = ingrid[(i-1):(i+1),(j-1):(j+1)]
if(sum(is.na(subg))==9){
outgrid[i,j] = ingrid[i,j]
}else{
vec = as.vector(subg)
ma = which.max(subg)
mi = which.min(subg)

   if((ma==5||mi==5)==T){
 outgrid[i,j] = median(subg,na.rm=T)  # apply median filter if there is peak 3
}else{
  outgrid[i,j] = ingrid[i,j]
}
}
}else{
 outgrid[i,j] = ingrid[i,j]
}

 }
}
outgrid
}


In [620]:
def filt3(lon, lat, ingrid, grid5):
    """
    Find peaks in 3 directions. FLag as 3
    """
    
    outgrid = ingrid*0   #make all zeros. in python if matrix ingrid has null values, they'll stay null after (*0)
    l1=len(lon)
    l2=len(lat)
    
    
    for i in range(3, l1-1):   #tem de ser -1 em vez de -2 
        for j in range(3, l2-1):
            if (grid5[i,j]==0):
                subg = ingrid[(i-2):(i+1), (j-2):(j+1)]
                if np.isnan(subg).sum()==9:
                    outgrid[i-1,j-1] = ingrid[i-1,j-1]
                else:
                    vec = np.array(subg).T.flatten()
                    ma = np.where(subg == np.amax(subg))
                    mi = np.where(subg == np.amin(subg))
                    
                    if ((ma==(1,1) or mi==(1,1))):     #pixel do meio
                        outgrid[i-1,j-1] = nanmedian(subg)
                    else:
                        outgrid[i-1,j-1] = ingrid[i-1,j-1]
            
            else:
                outgrid[i-1,j-1] = ingrid[i-1,j-1]
                
    return outgrid

#### Quanto à função filt3 penso estar tudo correto

## Verificação passo a passo da conversão da função filt3 de R para python

In [621]:
    
grid5 = filt5(lon=lon, lat=lat, ingrid=ingrid)
 
ingrid = np.arange(1,91).reshape(6, 15)     
outgrid = ingrid*0   #make all zeros. in python if matrix ingrid has null values, they'll stay null after (*0)
l1=len(lon)
l2=len(lat)
    
for i in range(3, l1-1):   
    for j in range(3, l2-1):
        if (grid5[i,j]==0):
            subg1 = ingrid[(i-2):(i+1), (j-2):(j+1)]
            if np.isnan(subg1).sum()==9:
                outgrid[i-1,j-1] = ingrid[i-1,j-1]
            else:
                vec = np.array(subg1).T.flatten()    ## convert matrix to vector
                ma = np.where(subg1 == np.amax(subg1))
                mi = np.where(subg1 == np.amin(subg1))
                    
                if ((ma==(1,1) or mi==(1,1))):     #pixel do meio
                    outgrid[i-1,j-1] = nanmedian(subg1)
                else:
                    outgrid[i-1,j-1] = ingrid[i-1,j-1]
            
        else:
            outgrid[i-1,j-1] = ingrid[i-1,j-1]
                

In [622]:
grid5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [623]:
vec

array([42, 57, 72, 43, 58, 73, 44, 59, 74])

In [624]:
outgrid

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,  0,  0],
       [ 0,  0, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

# Implementação do BOA

In [ ]:
#' boa
#'
#' @param lon longitude (vector) of the satellite image
#' @param lat latitude (vector) of the satellite image
#' @param ingrid The satellite data (matrix). If using chlorophyll, transform using log(ingrid))
#' @param nodata value representing 'no data'
#' @param direction Logical. Should direction be calculated and returned
#'
#' @return either a stand alone asc grid of front gradient data or a list of:
#'		grdir : ascii grid Gradient direction
#'    front : Gradient magnitude. In the case of chlorophyll, this is a ratio
#' @references Belkin, I. M. & O'Reilly, J. E. An algorithm for oceanic front detection in chlorophyll and SST satellite imagery. Journal of Marine Systems, 2009, 78, 319 - 326
#' @details Note: These grids are in raster format, as is used in \code{\link{raster}}. 
#' @keywords sst, chl, front, satellite
#' @export
#'
#' @examples # none
boa <-
function(lon, lat, ingrid, nodata = NA, direction = F){

## Workhorse filter from EBImage. Modified so we don't need colorspace and other annoying requirements.		
	.filter2 <-
		function (x, filter) 
		{
			# Workhorse filter from EBImage. Modified so we don't need colorspace and other annoying requirements.
			validObject(x)
			validObject(filter)
			#if (colorMode(x) == TrueColor) 
			#   stop("this method doesn't support the 'TrueColor' color mode")
			dx = dim(x)
			#cmx = colorMode(x)
			df = dim(filter)
			if (any(df%%2 == 0)) 
				stop("dimensions of 'filter' matrix must be odd")
			if (any(dx[1:2] < df)) 
				stop("dimensions of 'x' must be bigger than 'filter'")
			cx = dx%/%2    #divisão inteira
			cf = df%/%2    #divisão inteiracr
			wf = matrix(0, nr = dx[1], nc = dx[2])     #matrix of zeros with dimensions of x (dim(x)=dx)
			wf[(cx[1] - cf[1]):(cx[1] + cf[1]), (cx[2] - cf[2]):(cx[2] + cf[2])] = filter
			wf = fft(wf)
			dim(x) = c(dx[1:2], prod(dx)/prod(dx[1:2]))
			index1 = c(cx[1]:dx[1], 1:(cx[1] - 1))
			index2 = c(cx[2]:dx[2], 1:(cx[2] - 1))
			pdx = prod(dim(x)[1:2])
            
            ## Não estou a conseguir implementar esta parte
			y = apply(x, 3, function(xx) {
				dim(xx) = dx[1:2]   #dim(xx) is equal to dimensions of matrix x (dim(x)=dx)
				Re(fft(fft(xx) * wf, inverse = T)/pdx)[index1, index2]
			})
			dim(y) = dx
			y
		}	
	
	# browser()
    
    
#======================================================#
# Main BOA algorithm
#======================================================#
# require(adehabitat)
# x component (longitudinal kernel)
gx = matrix(c(-1,0,1,-2,0,2,-1,0,1),nrow=3, byrow=T)
# y component (latitudinal kernel)
gy = matrix(c(1,2,1,0,0,0,-1,-2,-1),nrow=3, byrow=T)
# filt 5 and 35 don't like NA's... but final steps are ok with it!

# if nodata is numeric, this will take care of it..
ingrid[ingrid == nodata] = -9999      ##NÂO ESTOU A PERCEBER   
# if something else: 
if(any(is.infinite(ingrid)|is.nan(ingrid)|is.na(ingrid))){
ingrid[is.na(ingrid)] = -9999       ## TO FIND MISSING VALUES. IF THE VALUE IS NA RETURN TRUE OTHERWISE FALSE
ingrid[is.nan(ingrid)] = -9999      ##CHECK IF MATRIX HAS ANY NaN (NOT A NUMBER) VALUE AS ELEMENT
ingrid[is.infinite(ingrid)] = -9999    ## CHECK TO SEE IF THE VECTOR CONTAINS INFINITE VALUES AS ELEMENTS
}

# do the median filtering
grid5 = filt5(lon, lat, ingrid, nodata = nodata)
grid35 = filt3(lon, lat, ingrid, grid5)

# make an index of bad values and land pixels.
grid35[grid35==-9999] = NA
naidx = is.na(grid35)
# convert these to zeros for smoothing purposes
grid35[naidx]=0
# perform the smoothing (Sobel filter)
tgx = .filter2(grid35, gx)
tgy = .filter2(grid35, gy)

# NOTE!! IDL CONVOL uses NORMALIZE function which defaults to the abs(sum(KERNEL)), in this case gx and gy
tx = tgx/sum(abs(as.vector(gx)), na.rm=T)
ty = tgy/sum(abs(as.vector(gy)), na.rm=T)
front = (sqrt(tx^2+ty^2))

    
#======================================================#
# landmask and edge dilation
#======================================================#
land = naidx*1
# land = naidx*1
land[land==1] = NaN
land[!is.nan(land)] = 1
# # use adehabitat library for image erosion (expand land pixels slightly)
# mask = morphology(as.asc(land, min(lon), yll = min(lat), cellsize = diff(lat)[1]), 'erode', 1)
# # remove edge pixels
# l1 = length(lon)
# l2 = length(lat)
# midx = mask*NaN
# midx[5:(l1-3), 5:(l2-3)]=1
# mask = mask*midx
# # account for the edge effect
# front = front *mask

    
    
#======================================================#
# landmask and edge dilation using raster!
#======================================================#


l1 = length(lon)
l2 = length(lat)

midx = land*NaN

midx[5:(l1-3), 5:(l2-3)] = 1

# land = land*midx

land = (land*midx)

# ssr = flip(t(raster(front)), 2)
ssr = flip(raster((t(front))),2)
extent(ssr) = c(min(lon), max(lon), min(lat), max(lat))

mask = flip(focal(raster(t(land)), w = matrix(c(0,0,0,0,1,0,0,0,0), nrow=3, ncol=3)), direction = 2)
extent(mask) = c(min(lon), max(lon), min(lat), max(lat))

front = mask*ssr


if(direction==T){
# ;   ************************************
# ;   *** Calculate Gradient Direction ***
# ;   ************************************
    GRAD_DIR = atan2(tgy@.Data, tgx@.Data)

# ;===> change radians to degrees
GRAD_DIR = GRAD_DIR*180/pi

# ;===> Adjust to 0-360 scheme (make negative degrees positive)
OK = which(GRAD_DIR < 0)
if(length(OK)>1)GRAD_DIR[OK] = 360 - abs(GRAD_DIR[OK])

# ;===> Convert degrees so that 0 degrees is North and East is 90 degrees
GRAD_DIR = (360 - GRAD_DIR + 90) %% 360

GRAD_DIR = flip(raster(t(GRAD_DIR)), direction = 2)
extent(GRAD_DIR) = extent(front)

list(grdir = GRAD_DIR*mask, front = front)
}
else{
front
}
}

## Verificação passo a passo da conversão da função filt2 de R para python

In [742]:
x = np.arange(1,91).reshape(6, 15)    #check
filt = np.arange(1,10).reshape(3,3)   #check
dx = x.shape                          #check   -> é uma tuple
df = filt.shape                       #check   -> é uma tuple
cx = tuple(elem//2 for elem in dx)    #check   -> é uma tuple
cf = tuple(elem//2 for elem in df)    #check   -> é uma tuple

wf = np.zeros(shape=dx)               #check     -> é numpy array
wf

wf[cx[0]-cf[0]-1:cx[0]+cf[0], cx[1]-cf[1]-1:cx[1]+cf[1]] = filt     #check

wf = fft2(wf)                        #check CARALHOOOOOOOOOO
wf

array([[ 4.50000000e+01+0.00000000e+00j, -3.57419117e+01-2.29514941e+01j,
         1.50790732e+01+3.19794122e+01j,  2.07294902e+00-2.48459823e+01j,
        -6.09090400e+00+1.18010808e+01j,  4.44089210e-16-5.19615242e+00j,
         5.42705098e+00+8.30223851e+00j, -3.24625742e+00-1.40278512e+01j,
        -3.24625742e+00+1.40278512e+01j,  5.42705098e+00-8.30223851e+00j,
        -8.88178420e-16+5.19615242e+00j, -6.09090400e+00-1.18010808e+01j,
         2.07294902e+00+2.48459823e+01j,  1.50790732e+01-3.19794122e+01j,
        -3.57419117e+01+2.29514941e+01j],
       [-2.85000000e+01-1.81865335e+01j,  1.32724413e+01+2.98216230e+01j,
         4.40778336e+00-2.74956222e+01j, -1.32877894e+01+1.53090025e+01j,
         1.05152895e+01-4.17165317e+00j, -3.00000000e+00+1.73205081e+00j,
        -2.09523786e-01-6.23640476e+00j, -3.32416989e+00+9.87512521e+00j,
         8.14794473e+00-7.66219265e+00j, -7.90851020e+00+2.56786228e+00j,
         3.00000000e+00-1.73205081e+00j, -6.95709321e-01+7.87987609e+0

In [743]:
#dim_x = [([dx[0:2], math.prod(dx)/math.prod(dx[0:2])]   #check
#dim_x
dim_x = np.array(dx[0:2])
dim_x =np.append(dim_x, math.prod(dx)/math.prod(dx[0:2]))     #check

aux1 = np.arange(cx[0],dx[0]+1)
aux2 = np.arange(1,cx[0])
index1 = np.concatenate((aux1, aux2), axis=None)               #check
index1 = index1-1

aux3 = np.arange(cx[1], dx[1]+1)
aux4 = np.arange(1,cx[1])
index2 = np.concatenate((aux3, aux4), axis=None)               #check
index2 = index2-1

pdx = math.prod(dim_x[0:2])                                   #check

y = (fft2(fft2(x)*wf)/pdx).real 
y = np.array([[y[i][j] for j in index2] for i in index1])

# Os resultados não são absolutamente iguais mas são parecidos (pode reverificar-se).
# Se houver problema é nas funções fft usadas

90.0

## Verificação passo a passo da conversão do Main BOA algorithm de R para python

In [ ]:
lon = np.array([1,2,3,4,5,6])
lat = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
ingrid = np.arange(1,91).reshape(6, 15) 

In [773]:
#======================================================#
# Main BOA algorithm                                   
#======================================================#

gx = np.matrix([[-1,0,1],[-2,0,2],[-1,0,1]])          #check  
gy = np.matrix([[1,2,1],[0,0,0],[-1,-2,-1]])          #check
        
np.nan_to_num(ingrid, nan=-9999, posinf=-9999, neginf=-9999)         #check
        
grid5 = filt5(lon, lat, ingrid, nodata = np.nan)          #check
grid35 = filt3(lon, lat, ingrid, grid5)                   #check

# make an index of bad values and land pixels.
grid35 = grid35.astype("float")
grid35[grid35 == -9999]=np.nan
naidx = np.isnan(grid35)  
naidx
# convert these to zeros for smoothing purposes
grid35[naidx]=0 

# perform the smoothing (Sobel filter)
tgx = filter2(grid35, gx)
tgy = filter2(grid35, gy)
tgy
        
tx = tgx/np.nansum(abs(np.array(gx).flatten()))
ty = tgy/np.nansum(abs(np.array(gy).flatten()))
front = np.sqrt((tx**2)+(ty**2))


#### Esta parte esta bem implementada (Main BOA algorithm)

In [762]:
def filter2(x, filt):
        
        dx = x.shape                          
        df = filt.shape                       
        cx = tuple(elem//2 for elem in dx)    
        cf = tuple(elem//2 for elem in df)    

        wf = np.zeros(shape=dx)               

        wf[cx[0]-cf[0]-1:cx[0]+cf[0], cx[1]-cf[1]-1:cx[1]+cf[1]] = filt    

        wf = fft2(wf)                        
    
        dim_x = np.array(dx[0:2])
        dim_x =np.append(dim_x, math.prod(dx)/math.prod(dx[0:2]))     

        aux1 = np.arange(cx[0],dx[0]+1)
        aux2 = np.arange(1,cx[0])
        index1 = np.concatenate((aux1, aux2), axis=None)  
        index1 = index1-1

        aux3 = np.arange(cx[1], dx[1]+1)
        aux4 = np.arange(1,cx[1])
        index2 = np.concatenate((aux3, aux4), axis=None) 
        index2 = index2-1

        pdx = math.prod(dim_x[0:2])                                   
        
        y = (fft2(fft2(x)*wf)/pdx).real 
        
        y = np.array([[y[i][j] for j in index2] for i in index1])
        
        return y
    

#### Esta função filter2 pode ter um erro nos fft -> verificar melhor

In [787]:
#======================================================#
# landmask and edge dilation
#======================================================#

land = naidx*1
land = land.astype("float")
land[land==1] = np.nan
land[~np.isnan(land)] = 1


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### Esta parte da Landmask and Edge Dilation está correta

In [806]:
#======================================================#
# landmask and edge dilation using raster!
#======================================================#

l1=lon.size                       #check
l2=lat.size                       #check

midx = land*np.nan                #check 

midx[2:(l1-1), 4:(l2-3)] = 1

land = np.multiply(land, midx)
land

################################## This part is hunting my nightmares
#ssr = flip(raster((t(front))),2)
#extent(ssr) = c(min(lon), max(lon), min(lat), max(lat))

#mask = flip(focal(raster(t(land)), w = matrix(c(0,0,0,0,1,0,0,0,0), nrow=3, ncol=3)), direction = 2)
#extent(mask) = c(min(lon), max(lon), min(lat), max(lat))

#front = mask*ssr
##################################

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan],
       [nan, nan, nan, nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan,
        nan, nan],
       [nan, nan, nan, nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan,
        nan, nan],
       [nan, nan, nan, nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan,
        nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan]])

In [809]:
front

array([[2.45114769e+01, 2.32896168e+01, 1.54616461e+01, 1.56312230e-15,
        3.28346894e-15, 1.94052184e+01, 2.78976926e+01, 2.85098667e+01,
        2.80100428e+01, 2.75102254e+01, 2.70104147e+01, 2.65106111e+01,
        2.60108151e+01, 2.55110270e+01, 2.50112475e+01],
       [1.70018381e+01, 1.32027459e+01, 5.83363094e+00, 9.28491675e-16,
        5.62434467e-15, 7.60139790e+00, 1.68393141e+01, 2.10014880e+01,
        2.05015243e+01, 2.00015624e+01, 1.95016025e+01, 1.90016447e+01,
        1.85016891e+01, 1.80017360e+01, 1.75017856e+01],
       [2.60412689e-15, 2.82457219e-15, 2.52637417e-15, 6.11059290e-16,
        2.09730572e-15, 2.82457219e-15, 2.82457219e-15, 1.57898386e-15,
        5.12683682e-15, 4.73695157e-16, 2.53745211e-15, 2.62439277e-15,
        2.52637417e-15, 2.53745211e-15, 2.55702773e-15],
       [2.57410995e-15, 3.11023750e-15, 4.39854005e-15, 1.72636134e-15,
        4.28892559e-15, 4.73695157e-15, 3.69630644e-15, 2.87006378e-15,
        3.89680452e-15, 2.53407233e-1

In [811]:
ssr = np.flip(raster(front.T),2)
ssr

NameError: name 'raster' is not defined

In [814]:
import arcpy
#ssr = arcpy.MakeRasterLayer_management("c:/workspace/image.tif", "rdlayer", "#", "feature.shp", "1")

ModuleNotFoundError: No module named 'arcpy'

In [812]:
ssr = arcpy.NumPyArrayToRaster(front.T, y_cell_size=1)
ssr

NameError: name 'arcpy' is not defined

## BOA in Python

In [760]:
def boa(lon, lat, ingrid, nodata = np.nan, direction = False):
    
    def filter2(x, filt):
        
        dx = x.shape                          
        df = filt.shape                       
        cx = tuple(elem//2 for elem in dx)    
        cf = tuple(elem//2 for elem in df)    

        wf = np.zeros(shape=dx)               

        wf[cx[0]-cf[0]-1:cx[0]+cf[0], cx[1]-cf[1]-1:cx[1]+cf[1]] = filt    

        wf = fft2(wf)                        
    
        dim_x = np.array(dx[0:2])
        dim_x =np.append(dim_x, math.prod(dx)/math.prod(dx[0:2]))     

        aux1 = np.arange(cx[0],dx[0]+1)
        aux2 = np.arange(1,cx[0])
        index1 = np.concatenate((aux1, aux2), axis=None)  
        index1 = index1-1

        aux3 = np.arange(cx[1], dx[1]+1)
        aux4 = np.arange(1,cx[1])
        index2 = np.concatenate((aux3, aux4), axis=None) 
        index2 = index2-1

        pdx = math.prod(dim_x[0:2])                                   
        
        y = (fft2(fft2(x)*wf)/pdx).real 
        
        y = np.array([[y[i][j] for j in index2] for i in index1])
        
        return y
    
   
    
#======================================================#
# Main BOA algorithm                                   
#======================================================#      
    gx = np.matrix([[-1,0,1],[-2,0,2],[-1,0,1]])   
    gy = np.matrix([[1,2,1],[0,0,0],[-1,-2,-1]])
        
    np.nan_to_num(ingrid, nan=-9999, posinf=-9999, neginf=-9999) ##replace NaN and inf values with -9999
        
    grid5 = filt5(lon, lat, ingrid, nodata = nodata)
    grid35 = filt3(lon, lat, ingrid, grid5)

    # make an index of bad values and land pixels.
    grid35 = grid35.astype("float")
    grid35[grid35 == -9999]=np.nan
    naidx = np.isnan(grid35)       
    # convert these to zeros for smoothing purposes
    grid35[naidx]=0  

    # perform the smoothing (Sobel filter)  
    tgx = filter2(grid35, gx)
    tgy = filter2(grid35, gy)
        
    tx = tgx/np.nansum(abs(np.array(gx).flatten()))
    ty = tgy/np.nansum(abs(np.array(gy).flatten()))
    front = np.sqrt((tx**2)+(ty**2))


#======================================================#
# landmask and edge dilation
#======================================================#

    land = naidx*1
    land = land.astype("float")

    land[land==1] = np.nan
    land[~np.isnan(land)] = 1

    
#======================================================#
# landmask and edge dilation using raster!
#======================================================#

    l1=lon.size    #using size because lon and lat are matrices
    l2=lat.size

    midx = land*np.nan

    midx[5:(l1-2), 5:(l2-2)] = 1

    land = np.multiply(land, midx)

    ################################## Não consigo converter isto para python
    ssr = flip(raster((t(front))),2)
    extent(ssr) = c(min(lon), max(lon), min(lat), max(lat))

    mask = flip(focal(raster(t(land)), w = matrix(c(0,0,0,0,1,0,0,0,0), nrow=3, ncol=3)), direction = 2)
    extent(mask) = c(min(lon), max(lon), min(lat), max(lat))

    front = mask*ssr
    ##################################


    if direction==True:
#   ************************************
#   *** Calculate Gradient Direction ***
#   ************************************
        GRAD_DIR = atan2(tgy@.Data, tgx@.Data)     ## NÃO COMPREENDO
        # ata2() -> function returns the radian arctangent between the x-axis and the vector from the origin to (x, y).

        # ;===> change radians to degrees
        GRAD_DIR = GRAD_DIR*180/math.pi

        # ;===> Adjust to 0-360 scheme (make negative degrees positive)
        OK = np.where(GRAD_DIR < 0)     ## retorna index da matriz cujos valores são negativos

        if grad[OK].size >1:
            GRAD_DIR[OK] = 360 - abs(GRAD_DIR[OK])

        # ;===> Convert degrees so that 0 degrees is North and East is 90 degrees
        GRAD_DIR = (360 - GRAD_DIR + 90) % 360     

        GRAD_DIR = flip(raster(t(GRAD_DIR)), direction = 2)       ## NÃO CONSIGO CONVERTER PARA PYTHON
        extent(GRAD_DIR) = extent(front)    
        #extent -> recebe matriz com 4 elementos e retorna a class Extent com (xmin, xmax,ymin, ymax)

        list(grdir = np.multiply(GRAD_DIR, mask), front = front)   
    
    else:
        front
    



SyntaxError: invalid syntax (845762282.py, line 105)